Repository chainhackers/superhack-2023, pull requests merged in 2023-08, with the labels that each got.

#5 3 game registry interface
  .gitignore
  README.md
  src/GameRegistry.sol
  src/interfaces/IGameRegistry.sol
Labels: enhancement

#6 add skeleton abstract class for games #4
  backend/game.py
Labels: enhancement

#12 IGame.sol cleanup and tests #1
  src/BattleShip.sol
  src/Counter.sol
  src/interfaces/IGame.sol
  test/BattleShip.t.sol
  test/Counter.t.sol
Labels: documentation, enhancement, contracts

#13 8 Vite Project and Redux Container
  .gitignore
  vite/.eslintrc.cjs
  vite/index.html
  vite/package.json
  vite/public/favicon.svg
  vite/src/App.tsx
  vite/src/api/api.ts
  vite/src/api/contractAbis/abi.json
  vite/src/api/contractMethodRequest.ts
  vite/src/main.tsx
  vite/src/store/api/apiActionTypes.ts
  vite/src/store/api/apiActions.ts
  vite/src/store/api/apiReducer.ts
  vite/src/store/game/gameActionTypes.ts
  vite/src/store/game/gameActions.ts
  vite/src/store/game/gameReducer.ts
  vite/src/store/modal/modalActionTypes.ts
  vite/src/store/modal/modalActions.ts
  vite/src/store/modal/modalReducer.ts
  vite/src/store/rootReducer.ts
  vite/src/store/store.ts
  vite/src/store/wallet/walletActionTypes.ts
  vite/src/store/wallet/walletActions.ts
  vite/src/store/wallet/walletReducer.ts
  vite/src/styles.css
  vite/src/typings/apiType.d.ts
  vite/src/typings/type.d.ts
  vite/src/wagmi/ethers.ts
  vite/src/wagmi/wagmiConfig.ts
  vite/tsconfig.json
  vite/tsconfig.node.json
  vite/vite.config.ts
  vite/yarn.lock
Labels: client

#14 add contract listener and event logger
  backend/BACKEND_README.md
  backend/battleship.py
  backend/constants.py
  backend/event_generator.py
  backend/log_setup.py
Labels: backend

#19 Frontend deploy #16
  .github/workflows/vite.yml
  vite/package.json
  vite/yarn.lock
Labels: enhancement

#21 remove methods from game.py and battleship.py, fix bits after review,…
  backend/BACKEND_README.md
  backend/battleship.py
  backend/game.py
  backend/local_testing/event_generator.py
  backend/requirements.txt
Labels: backend

#29 7, 22 Grid View and Transaction Popup
  .github/workflows/vite.yml
  vite/package.json
  vite/public/assets/img/cells.png
  vite/public/assets/img/cellsHover.png
  vite/src/App.tsx
  vite/src/api/api.ts
  vite/src/api/contractAbis/abi.json
  vite/src/api/contractAbis/iGrid.json
  vite/src/components/Overlay/Overlay.module.css
  vite/src/components/Overlay/Overlay.tsx
  vite/src/components/Popup/Popup.module.css
  vite/src/components/Popup/Popup.tsx
  vite/src/components/Popup/TransactionLink/TransactionLink.module.css
  vite/src/components/Popup/TransactionLink/TransactionLink.tsx
  vite/src/components/gameView/GameView.tsx
  vite/src/game/constants/assetConstants.ts
  vite/src/game/constants/gameConstants.ts
  vite/src/game/objects/cell.ts
  vite/src/game/objects/cellsGrid.ts
  vite/src/game/scenes/gameScene.ts
  vite/src/game/scenes/preloadGameScene.ts
  vite/src/store/game/gameActions.ts
  vite/src/styles.css
  vite/src/typings/fileType.d.ts
  vite/src/typings/type.d.ts
  vite/src/wagmi/ethers.ts
  vite/src/wagmi/wagmiConfig.ts
  vite/tsconfig.json
  vite/vite.config.ts
  vite/yarn.lock
Labels: enhancement, client

#32 IGrid.sol: add cellDetails(x,y) #31
  contracts/src/Grid.sol
  contracts/src/interfaces/IGrid.sol
Labels: enhancement, contracts

#28 Add integration of ZkProof generator #18
  .gitignore
  backend/BACKEND_README.md
  backend/battleship.py
  backend/constants.py
  backend/utils.py
  backend/zokrates.py
  contracts/README.md
Labels: enhancement

#40 23 Load cell image from URL
  .github/workflows/vite.yml
  vite/src/App.tsx
  vite/src/api/api.ts
  vite/src/api/contractAbis/iGrid.json
  vite/src/components/gameView/GameView.tsx
  vite/src/game/constants/assetConstants.ts
  vite/src/game/constants/gameConstants.ts
  vite/src/game/objects/cell.ts
  vite/src/game/scenes/gameScene.ts
  vite/src/game/scenes/preloadGameScene.ts
  vite/src/typings/apiType.d.ts
Labels: client

#38 BattleShipDeploy.s.sol #36
  README.md
  backend/battleship.py
  backend/zokrates.py
  contracts/.gitignore
  contracts/script/BattleShipDeploy.s.sol
  contracts/script/GameRegistryDeploy.s.sol
  contracts/script/GameRegistryUpgrade.s.sol
  contracts/script/IUpgradeable.sol
  contracts/src/BattleShip.sol
  contracts/src/GameRegistry.sol
  contracts/src/interfaces/IGame.sol
  contracts/src/interfaces/IGameRegistry.sol
  contracts/src/interfaces/IGrid.sol
  contracts/src/verifiers/battleship_init.sol
  contracts/src/verifiers/battleship_move.sol
  contracts/src/verifiers/pairing.sol
  contracts/test/BattleShip.t.sol
Labels: enhancement, backend, contracts
